name: Ruby

on: pull_request

jobs:
  tests:
    name: Rubocop and Tests
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 3.0
        uses: actions/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.0.x
      - name: Install dependencies
        run: bundle install
      - name: Run Tests
        run: bundle exec rake test
